### ISSUE TITLE
Dependency free version (no uCrop)

### ISSUE THREAD

**Issue by MFlisar** [FuckBoilerplate/RxPaparazzo#12]
Is it possible to split the library into two parts, one with crop support (and the corresponding dependency to uCrop) and one without?

So that we end up with a usage like following:

    compile "com.github.FuckBoilerplate:RxPaparazzo:0.1.0"
    compile "com.github.FuckBoilerplate:RxPaparazzo-crop:0.1.0"

so that someone who does not want to include uCrop can still use your library?

**Comment by VictorAlbertos** [comment]
I don't think UCrop library adds too much overhead, even if you are not willing to use it.

Nevertheless, you can exclude the module ucrop explicitly when requesting RxPaparazzo dependency from Graddle. 

```
compile("com.github.FuckBoilerplate:RxPaparazzo:0.1.0") {
        exclude module: 'crop’
    }
```

Doing that UCrop artifact will be excluded. But be aware that any call to crop method will throw now an exception.

**Comment by MFlisar** [comment]
Thanks, that's actually enough
