### ISSUE TITLE
Request is null after calling camera intent

### ISSUE THREAD

**Issue by MFlisar** [FuckBoilerplate/RxPaparazzo#13]
I get following exception:

	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'rx_activity_result.OnResult rx_activity_result.Request.onResult()' on a null object reference
	at rx_activity_result.HolderActivity.onCreate(HolderActivity.java:33)
	at android.app.Activity.performCreate(Activity.java:6374)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855) 
	at android.app.ActivityThread.access$900(ActivityThread.java:181) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
	at android.os.Handler.dispatchMessage(Handler.java:102) 
	at android.os.Looper.loop(Looper.java:145) 
	at android.app.ActivityThread.main(ActivityThread.java:6117) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at java.lang.reflect.Method.invoke(Method.java:372) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 

This is how I use it:

    @Override
    public boolean onMenuItemClick(MenuItem item)
    {
        switch (item.getItemId())
        {
            case R.id.action_camera:
            {
                // does take care of camera permission!!!
                RxPaparazzo.takeImage(getActivity())
                        .usingCamera()
                        .subscribe(response -> {
                            if (response.resultCode() != Activity.RESULT_OK)
                                return;
                            onImageTaken(response.targetUI(), response.data());
                        });
                break;
            }
    }

Any idea why this happens? In my Application I do call `RxPaparazzo.register(this);`...

Some sideeffect is, that the image is not even saved...

**Comment by MFlisar** [comment]
PS: following manual approach works though:

	@Override
	public boolean onMenuItemClick(MenuItem item)
	{
		switch (item.getItemId())
		{
			case R.id.action_camera:
			{
				// does take care of camera permission!!!
				Intent takePhoto =  new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
				Observable<Boolean> obsPermission = RxPermissions.getInstance(getActivity()).request(Manifest.permission.CAMERA);
				Observable<Result<MainActivityMVP>> obsFoto = RxActivityResult.on(getActivity()).startIntent(takePhoto);
				obsPermission
						.zipWith(obsFoto, (aBoolean, result) -> aBoolean ? result : null)
						.subscribe(result -> {
							if (result == null) // Permission denied, cancelled, ...
								return;
							Intent data = result.data();
							int resultCode = result.resultCode();

							if (resultCode == Activity.RESULT_OK)
								onImageTaken(result.targetUI(), data.getData().toString());
						});
				break;
		}
	}

I know, zip is not the correct operator, I should use something like "if permission request succeeded, then take photo"...

**Comment by VictorAlbertos** [comment]
You need to call the method `onImageTaken` using the `targetUI()` method, as follows:

`targetUI().onImageTaken()`

This is because this method holds a reference to current valid instance of your fragment or activity.

Try this and let me know.

**Comment by MFlisar** [comment]
I am using a helper class and oversaw that and thought I'm passing the activity itself to the function anyway... thanks

**Comment by sagartrehan** [comment]
@VictorAlbertos 
I am getting exactly same crash and I here is how I am invoking Fragment method:

```
private Subscriber<Response<ProfileFragment, String>> getImageSelectorAction() {
        return new Subscriber<Response<ProfileFragment, String>>() {
            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable e) {

            }

            @Override
            public void onNext(Response<ProfileFragment, String> response) {
                if (response.resultCode() != Activity.RESULT_OK) {
                    return;
                }
                response.targetUI().loadProfileImage(response.data());
            }
        };
    }
```

Please let me know if I accessing loadProfileImage() method in wrong way.

**Comment by VictorAlbertos** [comment]
Can you post the stack trace please?

**Comment by sagartrehan** [comment]
@VictorAlbertos 
Thanks for the quick response. Updated comment with crash stacktrace.

**Comment by VictorAlbertos** [comment]
Implement the `Subscriber` without calling `getImageSelectorAction`, yes, I'm asking you to duplicate code right now ;)

And let me know.

**Comment by sagartrehan** [comment]
@VictorAlbertos 
I have updated the code as mentioned,  I will test it on my friends device and will provide you feedback.

Thanks

**Comment by sagartrehan** [comment]
@VictorAlbertos 
No Victor doing this not fixed the issue app is still crashing. Please let me know if I can add some hack as of now to fix issue temporarily

**Comment by VictorAlbertos** [comment]
@sagartrehan, if you can create a repo which isolates the bug and tell me how to reproduce it with an specific android simulator, I'll be able to help you more. Otherwise, I think I can't do much more. Sorry.
