### ISSUE TITLE
how can we use UCrop features?

### ISSUE THREAD

**Issue by omegasoft7** [FuckBoilerplate/RxPaparazzo#16]
Hi

There are some features in UCrop lib that i need to use it on my project. 
Features like:

UCrop.of(sourceUri, destinationUri)
    .withAspectRatio(16, 9)
    .withMaxResultSize(maxWidth, maxHeight)
    .start(context);

Can we make more options like Size that we have and pass these parameters as well?

**Comment by VictorAlbertos** [comment]
Hi @omegasoft7 

No, it's not possible. You can only change properties defined in the UCrop.Option class. Sorry.

```java
        UCrop.Options options = new UCrop.Options();
        RxPaparazzo.takeImage(this)
                .crop(options)
                .usingCamera();
```

You can ask to the UCrop authors to add to the UCrop.Options the properties which you need. Or do a PR yourself 👍

**Comment by omegasoft7** [comment]
I think I can add this feature to RxPapparazo. Can I try it?

**Comment by VictorAlbertos** [comment]
It will depend on the resulting Api :)

Can you explain what would be the changes when calling RxPaparazzo?
 
Now:

```java
UCrop.Options options = new UCrop.Options();
        RxPaparazzo.takeImage(this)
                .crop(options)
                .usingCamera();
```

What is your proposal?

**Comment by omegasoft7** [comment]
i can add a new builder class for UCrop and call it after .crop(). Something similar with UCrop.Option but it will contain our options.

Similar with other builders it has default value and instead of setting Ucrop like: UCrop.of() we will use this builder.

I hope i could fully explain my idea. :)

**Comment by VictorAlbertos** [comment]
I think the problem is the intent reference inside the `UCrop` class. How to retrieve its configurations without exposing an intent from RxPaparazzo? 

I think you will need to expose an intent when calling RxPaparazzo.crop(intent). But try to implement it and we will se how to adjust the api afterwards ;)

**Comment by omegasoft7** [comment]
sure working on it :)

**Comment by omegasoft7** [comment]
Done, I just couldnt fully test it on my side. Please let me know if something is not as expected

**Comment by VictorAlbertos** [comment]
You can now use the requested features:
 
`compile "com.github.FuckBoilerplate:RxPaparazzo:0.1.2"`

Take a look at the readme with the new info about how to use it ;)

If you are interested in knowing the implementation check this [commit](https://github.com/FuckBoilerplate/RxPaparazzo/commit/2b0c9f6230a775dbeca1ffd9a3fd27c203db6460).
