### ISSUE TITLE
RxPparazzo retrieves the same images when I select more than one image

### ISSUE THREAD

**Issue by igiagante** [FuckBoilerplate/RxPaparazzo#19]
Hi guys, I added this [question](http://stackoverflow.com/questions/37750453/rxpparazzo-retrieves-the-same-images-when-i-select-more-than-one-image) in Stackoverflow. If you need more information, let me know. 

I updated the last version, but I'm still having the same issue. I'll appreciate a lot your help. Thanks!

**Comment by VictorAlbertos** [comment]
This issues has been fixed with the [release 0.1.3 ](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.1.3)
