### ISSUE TITLE
RxPaparazzo duplicate images when it selects from gallery

### ISSUE THREAD

**Issue by igiagante** [FuckBoilerplate/RxPaparazzo#20]
Hi guys,

I would like to know why paparazzo is creating new images when I select images from the gallery. Check the last question to find the stackoverflow's link to see the update. I uploaded a video that shows the duplication.

Thank for fixing the other issue so fast.

**Comment by miguelbcr** [comment]
Hi @igiagante!,

I think it should be the right behaviour. Anyway take a look to [this issue](https://github.com/FuckBoilerplate/RxPaparazzo/issues/6) where I explain how the library works and how to deal with duplicate images.
