### ISSUE TITLE
Using normal onActivityResult in fragment

### ISSUE THREAD

**Issue by canberkcakmak** [FuckBoilerplate/RxPaparazzo#22]
Options options = new Options();
        options.setToolbarColor(ContextCompat.getColor(getActivity(), R.color.colorAccent));
        options.setAspectRatio(500, 500);

 RxPaparazzo.register(this);

Firstly, thanks for perfect library. But, i have a problem with using onActivityResult. I know you dont like this but, my project gives some error with your solution. So how can i get path of image when photo cropped? Thank you

`public void onActivityResult(int requestCode, int resultCode, Intent data) {

    if (requestCode == REQUEST_GALLERY && resultCode == Activity.RESULT_OK&& null != data) {

        return;
    }
}`
i want to both of camera and gallery code for my project. Thanks

By the way i'm using for choose photo and crop, with this code: 
size = Size.Original; RxPaparazzo.takeImage(this) .size(size) .crop(options) .usingCamera() .subscribe();

is this true?

**Comment by VictorAlbertos** [comment]
HI @canberkcakmak 

Sorry, but I can't understand the problem. I'm only can advice you to check the [example](https://github.com/FuckBoilerplate/RxPaparazzo/blob/master/app/src/main/java/com/fuck_boilerplate/rx_paparazzo/sample/fragments/SampleFragment.java) using a fragment.

**Comment by canberkcakmak** [comment]
I said, you were used this method for get image path : `.subscribe(response -> {
                    if (response.resultCode() != Activity.RESULT_OK) {
                        response.targetUI().showUserCanceled();
                        return;
                    }

                    response.targetUI().loadImage(response.data());
                });`

But i want this method: 
`if (requestCode == REQUEST_GALLERY && resultCode == Activity.RESULT_OK&& null != data) {

    return;
}
}``

how can i convert it?

**Comment by VictorAlbertos** [comment]
You need to specify previously what component to use. Pick camera or gallery, but you can't use both of them in the same intent call. But again, I'm not sure about the question.

**Comment by canberkcakmak** [comment]
But it never @Override in onActivityResult. In debug mode, it never returns or enter in this part : 
`@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == RESULT_OK && requestCode == UCrop.REQUEST_CROP) {
            final Uri resultUri = UCrop.getOutput(data);
       
        } else if (resultCode == UCrop.RESULT_ERROR) {
            final Throwable cropError = UCrop.getError(data);
        }
    }`
