### ISSUE TITLE
How to save Image in internal storage instead of external storage

### ISSUE THREAD

**Issue by sagartrehan** [FuckBoilerplate/RxPaparazzo#23]
I am using library for selecting user profile image and crop. It's work pretty well for me. But I do not want to take external storage permission from user for saving selected/cropped image. 

I just need to save image on temporary basis so if I can save temporary image in internal storage then it would be best for me. As doing this way I can avoid external Storage permission.

Query: Can we have provision in library so that we can save image in internal storage instead or external. 

Waiting for your earliest reply.

**Comment by miguelbcr** [comment]
Hi @sagartrehan,
We are working on it so I'll tell you something asap.

**Comment by miguelbcr** [comment]
Hi @sagartrehan,
sorry for the late...

We've released [version 0.1.5](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.1.5).
Now you can use `.useInternalStorage()` on RxParazzo builder as the same way as `.crop()` or `.size()`

Try it out and let us know if it works for you.

**Comment by sagartrehan** [comment]
Thanks @miguelbcr for this update to save image in internal storage. 
Now can I avoid 
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
permission from user, If I am using internal storage for saving image?

 I will give it a try today.


Thanks

**Comment by miguelbcr** [comment]
Hi @sagartrehan,
sorry, I forgot to manage the permissions.

We've released [version 0.1.6](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.1.6)

Now if you use `.useInternalStorage()` no dialog will be showed to ask you for external storage permissions, in spite of being necessary on RxPaparazzo library declared in [Manifest](https://github.com/FuckBoilerplate/RxPaparazzo/blob/master/rx_paparazzo/src/main/AndroidManifest.xml).

**Comment by hemb** [comment]
Thanks for this update @miguelbcr,

Just one issue. I want to pick an image from the gallery, but save the result to internal storage. So when `.useInternalStorage()` is used together with `usingGallery()`, RxPaparazzo should still ask for READ_EXTERNAL_STORAGE permission.

**Comment by miguelbcr** [comment]
Hi @hemb,
thanks!, you are right, sorry, it was my fault by not testing it properly on Android 6.

We've released [version 0.1.7](https://github.com/FuckBoilerplate/RxPaparazzo/releases/tag/0.1.7)
Try it out and let us know if it works for you.

**Comment by hemb** [comment]
Works like a dream! Thanks!
