### ISSUE TITLE
Subscriber is not called for nested fragments :-(

### ISSUE THREAD

**Issue by egslava** [FuckBoilerplate/RxPaparazzo#5]
What can I do with it? Callback is called only when system asks for permissions. Other results are not reported.

**Comment by VictorAlbertos** [comment]
Hi @egslava 

I don't know if I understood you correctly, so please correct me if I'm wrong. 

Do you mean that when using nested fragments -and only nested fragments- the subscriber observable will only be consume the item when the system asks for permissions?

**Comment by egslava** [comment]
Hi @VictorAlbertos 
I made some animation + demo project. Please, see it:
https://github.com/egslava/bug-report-rx-paparazzo-nested-fragments

**Comment by VictorAlbertos** [comment]
What a great feedback ;)

Thanks, as soon as possible I'll clone your repo and I'll try to fix it.

**Comment by egslava** [comment]
Sorry, gif was a bit cutted off, so I uploaded original demo video to youtube.
https://youtu.be/s1RlfkxKKpw

Perhaps, do you have any ETA (day/week/month)? :-( Just need to know - if I need to fix it by workaround or I can just do some other tasks instead?

**Comment by VictorAlbertos** [comment]
The bug is fixed. 

I've done a pull request to your project upgrading the rxpaparazzo version, and as long I can tell, it works just fine.

Let me know ;)

**Comment by egslava** [comment]
Very-very thanks! :-) Great! :-) Thank you! Amazing lib! Good luck! :-)

**Comment by VictorAlbertos** [comment]
Thanks :) I'm closing this issues.
