### ISSUE TITLE
Fragment doesn't receive result of image pick

### ISSUE THREAD

**Issue by Tieru** [FuckBoilerplate/RxPaparazzo#7]
I'm trying to pick an image from gallery. I successfully launch gallery intent with this code but nothing happens after I select an image. None of "subscibe" callbacks get called. 
```
public class PhotosFragment extends Fragment {
...
	private void loadFromGallery() {
		RxPaparazzo.takeImage(this)
				.crop()
				.usingGallery()
				.subscribe(new Subscriber<Response<PhotosFragment, String>>() {
				@Override
				public void onCompleted() {
					Log.d("PhotosFragmentD", "On photo pick completed");
				}

				@Override
				public void onError(Throwable e) {
					e.printStackTrace();
				}

				@Override
				public void onNext(Response<PhotosFragment, String> response) {
					currentImagePath = response.data();
					response.targetUI().displayCaptionDialog();
				}
		});
	}
```

What's wrong with my code? How can I debug this issue?

**Comment by VictorAlbertos** [comment]
Hi @Tieru 

Are you using the last version of RxPaparazzo?

`compile "io.reactivex:rxjava:1.1.4"`

If so, is your PhotosFragment extending from `android.support.v4.app.Fragment`? Your fragment can't extend from `android.app.Fragment`, because it will not be noticed.  

I'm going to update the readme with this information.

**Comment by Tieru** [comment]
Everything looks fine in my code. 
```
    compile "com.github.FuckBoilerplate:RxPaparazzo:0.0.6"
    compile "io.reactivex:rxjava:1.1.4"
```
PhotosFragment extends android.support.v4.app.Fragment

I finished with calling this code from parent Activity. Everything works fine now, even though I still can't call picker from my fragment.

**Comment by VictorAlbertos** [comment]
Can you please try the new version using a Fragment again, and let me know?

`compile "com.github.FuckBoilerplate:RxPaparazzo:0.0.7"`

**Comment by Tieru** [comment]
Thank you! It works perfectly now. 

And thanks again for your great library!
